NAME = PhoneBook

SRC = PhoneBook.cpp

OBJ = $(SRC:.cpp=.o)

CC = c++

CFLAGS = -fsanitize=address -std=c++98 #-Wall -Wextra -Werror 

all:$(NAME)
$(NAME):$(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(NAME)

%.o: %.cpp  classes.hpp header.h
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: clean